### ISSUE TITLE
Example Fails

### ISSUE THREAD

**Issue by coreybutler** [kuoruan/v8go-polyfills#2]
None of these polyfills currently work. Running the example (i.e. `go run test.go`) with the code from the README fails with:

```
/go/pkg/mod/go.kuoruan.net/v8go-polyfills@v0.3.2/internal/version.go:26:2: package embed is not in GOROOT (/usr/local/go/src/embed)
```

It looks like the module is expecting a build-time version number.

**Comment by kuoruan** [comment]
Hi, this modules requires go 1.16, so you should update your golang version

**Comment by coreybutler** [comment]
Got it, thanks for the quick reply!
